twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
            visit_counter : '@App\Service\VisitCounter'

when@test:
    twig:
        strict_variables: true
